site_name: 大富翁量化
site_url: http://www.jieyu.ai/
repo_url: https://github.com/zillionare/zillionare
repo_name: zillionare
site_description: 量化软件 量化策略 量化课程 邢不行 CQF 大富翁 backtrader zipline CTA AI B圈 Python量化 聚宽 数字货币 金融大数据及量化分析
#strict: true

nav:
  - 最新文章: '/'
  - 量化课程:
    - 因子投资与机器学习策略:
      - 简介: articles/coursea/factor-ml/intro.md
      - 课程大纲: articles/coursea/factor-ml/syllabus.html
    - 量化二十四课:
      - 简介: articles/coursea/24lectures/intro.md
      - 课程大纲: articles/coursea/24lectures/syllabus.html
      - FAQ: articles/coursea/24lectures/faq.md
      - 内容详情: articles/coursea/24lectures/detail.md
      - 课程预览: articles/coursea/24lectures/preview.md
    - 量化中的Numpy和Pandas:
      - 简介: articles/coursea/numpy-pandas/intro.md
      - 课程大纲: articles/coursea/numpy-pandas/syllabus.html
  - 量化产品:
    - ... | articles/products/**
  - 策略研究:
    - ... | articles/investment/**
  - 学Python:
    - ... | articles/python/**
  - 文章分类: tags
  - Follow Us: 
    - contact.md
  - 福利: free-resources.md
theme:
  name: material
  language: zh
  logo: assets/img/logo.png
  custom_dir: docs/overrides
  palette:
    primary: light blue
  features:
    - navigation.indexes
    - navigation.tabs
    - navigation.instant
    - navigation.tabs.sticky
exclude_docs: |
  _drafts/**
  _archive/**
  videoscripts/**
markdown_extensions:
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - pymdownx.details
  - admonition
  - toc:
      baselevel: 1
      permalink: true
  - meta
  - pymdownx.arithmatex:
      generic: true
plugins:
  - include-markdown
  - awesome-pages:
      collapse_single_pages: true
  - blog:
      post_excerpt_separator: <!--more-->
  - tags:
      tags_file: tags.md
  - redirects:
      redirect_maps:
        'articles/coursea/cheese/intro.md': 'articles/coursea/24lectures/intro.md'
        'articles/coursea/cheese/outline.md': articles/coursea/24lectures/intro.md
        'blog/2024/01/24/finding-alphas-a-quantitative-approach.md': 'http://www.jieyu.ai/blog/2024/01/25/finding-alphas-a-quantitative-approach/'
  - rss:
      match_path: "(blog|articles)/.*"
      categories:
        - category
        - tags
      date_from_meta:
        as_creation: "date"
        as_update: true
        datetime_format: "%Y-%m-%d %H:%M"
        default_timezone: Asia/Shanghai
      use_git: false
  - search:
      lang: zh
extra:
  social:
    - icon: fontawesome/brands/qq
      link: http://qm.qq.com/cgi-bin/qm/qr?_wv=1027&k=zxYR3Hve6OMGLvEdgV4z_ONxcOF3hjMh&authKey=eoPjHqcwDIyiTQRNE6jGw1ReDajzXnGHtkAgwapdicr9n%2FPStD3FKit2miTi0zhC&noverify=0&group_code=578029127
      name: QQ群
    - icon: fontawesome/brands/zhihu
      link: https://www.zhihu.com/people/hbaaron
      name: 知乎
    - icon: fontawesome/brands/github
      link: https://github.com/zillionare
      name: Github
    - icon: material/email
      link: "mailto: aaron_yang@jieyu.ai"
  analytics:
    provider: google
    property: G-EHVH3XCS1V

extra_javascript:
  - overrides/javascripts/course.js
  # - assets/js/less.js
  - overrides/javascripts/katex.js
  - overrides/javascripts/katex.min.js
  - overrides/javascripts/auto-render.min.js

extra_css:
  - overrides/stylesheets/extra.css
  - overrides/stylesheets/katex.min.css
  # - assets/css/card.less
  # - assets/css/table.less
