name: dev build & test
on:
  push:
    branches: [ main, master, release ]
jobs:
  test:
    env:
      JQ_ACCOUNT: "${{secrets.JQ_ACCOUNT}}"
      JQ_PASSWORD: ${{secrets.JQ_PASSWORD}}
      GH_TOKEN: ${{ secrets.PERSONAL_TOKEN }}

      PYPI_INDEX_URL: https://pypi.org/simple
      INIT_BARS_MONTHS: 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive" 
          fetch-depth: 0       # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.12'
          architecture: 'x64'

      - name: Test docs building
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements_dev.txt
          mkdocs build

      - name: Test docker image building
        run: |
          make test
